export const INCOME_CREATE_REQUEST = "INCOME_CREATE_REQUEST";
export const INCOME_CREATE_SUCCESS = "INCOME_CREATE_SUCCESS";
export const INCOME_CREATE_FAIL = "INCOME_CREATE_FAIL";
export const INCOME_CREATE_RESET = "INCOME_CREATE_RESET";

export const GET_INCOMES_REQUEST = "GET_INCOMES_REQUEST";
export const GET_INCOMES_SUCCESS = "GET_INCOMES_SUCCESS";
export const GET_INCOMES_FAIL = "GET_INCOMES_FAIL";
export const GET_INCOMES_RESET = "GET_INCOMES_RESET";

export const INCOME_DELETE_REQUEST = "INCOME_DELETE_REQUEST";
export const INCOME_DELETE_SUCCESS = "INCOME_DELETE_SUCCESS";
export const INCOME_DELETE_FAIL = "INCOME_DELETE_FAIL";


export const INCOME_UPDATE_REQUEST = "INCOME_UPDATE_REQUEST";
export const INCOME_UPDATE_SUCCESS = "INCOME_UPDATE_SUCCESS";
export const INCOME_UPDATE_FAIL = "INCOME_UPDATE_FAIL";
export const INCOME_UPDATE_RESET = "INCOME_UPDATE_RESET";




export const INCOME_DETAILS_REQUEST = "INCOME_DETAILS_REQUEST"
export const INCOME_DETAILS_SUCCESS = "INCOME_DETAILS_SUCCESS"
export const INCOME_DETAILS_FAIL = "INCOME_DETAILS_FAIL"

export const TOTAL_TASKS_INCOME_REQUEST = "ITOTAL_TASKS_INCOME_REQUEST"
export const TOTAL_TASKS_INCOME_SUCCESS = "TOTAL_TASKS_INCOME_SUCCESS"
export const TOTAL_TASKS_INCOME_FAIL = "TOTAL_TASKS_INCOME_FAIL"


