

export const TASK_CREATE_REQUEST = "TASK_CREATE_REQUEST"
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS"
export const TASK_CREATE_FAIL = "TASK_CREATE_FAIL"
export const TASK_CREATE_RESET = "TASK_CREATE_RESET"

export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const GET_TASKS_FAIL = 'GET_TASKS_FAIL'
export const GET_TASKS_RESET = 'GET_TASKS_RESET'


export const GET_BIN_TASKS_REQUEST = 'GET_BIN_TASKS_REQUEST'
export const GET_BIN_TASKS_SUCCESS = 'GET_BIN_TASKS_SUCCESS'
export const GET_BIN_TASKS_FAIL = 'GET_BIN_TASKS_FAIL'
export const GET_BIN_TASKS_RESET = 'GET_BIN_TASKS_RESET'



export const BIN_TASKS_REQUEST = "BIN_TASKS_REQUEST"
export const BIN_TASKS_SUCCESS = "BIN_TASKS_SUCCESS"
export const BIN_TASKS_FAIL = "BIN_TASKS_FAIL"
export const BIN_TASKS_RESET = "BIN_TASKS_RESET"


export const UNBIN_TASKS_REQUEST = "UNBIN_TASKS_REQUEST"
export const UNBIN_TASKS_SUCCESS = "UNBIN_TASKS_SUCCESS"
export const UNBIN_TASKS_FAIL = "UNBIN_TASKS_FAIL"
export const UNBIN_TASKS_RESET = "UNBIN_TASKS_RESET"


export const UPDATE_TASKS_REQUEST = "UPDATE_TASKS_REQUEST"
export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS"
export const UPDATE_TASKS_FAIL = "UPDATE_TASKS_FAIL"
export const UPDATE_TASKS_RESET = "UPDATE_TASKS_RESET"


export const UPDATE_TASKS_STAGE_REQUEST = "UPDATE_TASKS_STAGE_REQUEST"
export const UPDATE_TASKS_STAGE_SUCCESS = "UPDATE_TASKS_STAGE_SUCCESS"
export const UPDATE_TASKS_STAGE_FAIL = "UPDATE_TASKS_STAGE_FAIL"
export const UPDATE_TASKS_STAGE_RESET = "UPDATE_TASKS_STAGE_RESET"


export const DETAILS_TASKS_REQUEST = "DETAILS_TASKS_REQUEST"
export const DETAILS_TASKS_SUCCESS = "DETAILS_TASKS_SUCCESS"
export const DETAILS_TASKS_FAIL = "DETAILS_TASKS_FAIL"
export const DETAILS_TASKS_RESET = "DETAILS_TASKS_RESET"




export const TASK_DELETE_REQUEST = "TASK_DELETE_REQUEST"
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS"
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL"


export const TASK_DETAILS_REQUEST = "TASK_DETAILS_REQUEST"
export const TASK_DETAILS_SUCCESS = "TASK_DETAILS_SUCCESS"
export const TASK_DETAILS_FAIL = "TASK_DETAILS_FAIL"
export const TASK_DETAILS_RESET = "TASK_DETAILS_RESET"
